name: Myfirst workflow 

on: 
  workflow_dispatch:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - release
    - main

jobs:
  myfirst_job:
    runs-on: ubuntu-latest

    steps:
      - name: Determine environment
        id: env
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if [ "${{github.event_name}}" == "push"]; then
            
            if [ "${BRANCH}" == "dev"]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [ "${{github.event_name}} == "pull_request" ]; then
             if [ "${{ github.base_ref }}" == "release"  ]; then
               echo "ENVIRONMENT=release" >> $GITHUB_ENV 
             elif [ "${{ github.base_ref }}" == "main"  ] ; then
                echo "ENVIRONMENT=release" >> $GITHUB_ENV           



      - name: showing the value
        run:
          echo "the value is $ENVIRONMENT"
          # echo "the value is $ENVIRONMENT2"

      
