name: Myfirst workflow 

on: 
  workflow_dispatch:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - release
    - main

jobs:
  myfirst_job:
    runs-on: ubuntu-latest

    steps:
      - name: Determine environment
        id: env
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}

            if [ "${GITHUB_EVENT_NAME}" == "push" ]; then
              if [ "${BRANCH}" == "dev" ]; then
                echo "ENVIRONMENT=dev" >> $GITHUB_ENV
              fi
            elif [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
              if [ "${BRANCH}" == "release" ]; then
                echo "ENVIRONMENT=release" >> $GITHUB_ENV
              elif [ "${BRANCH}" == "main" ]; then
                echo "ENVIRONMENT=release" >> $GITHUB_ENV
              fi
            fi


      - name: showing the value
        run:
          echo "the value is $ENVIRONMENT"
          # echo "the value is $ENVIRONMENT2"

      
