name: Myfirst workflow 

on: 
  workflow_dispatch:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - release
    - main

jobs:
  myfirst_job:
    runs-on: ubuntu-latest

    steps:
      - name: Determine environment
        id: env
        run: |
          echo "ENVIRONMENT1=${{ github.base_ref }}" >> $GITHUB_ENV
          echo "ENVIRONMENT2=${{ github.ref }}" >> $GITHUB_ENV

      - name: showing the value
        run:
          echo "the value is $ENVIRONMENT1"
          echo "the value is $ENVIRONMENT2"

      
