name: Myfirst workflow 

on: 
  workflow_dispatch:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - release
    - main

jobs:
  myfirst_job:
    runs-on: ubuntu-latest

    steps:
      - name: Determine environment
        id: env
        run: echo "ENVIRONMENT=${{ github.ref }}" 

      - name: showing the value
        run:
          echo "the value is $ENVIRONMENT"

      
